### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by aphillipo** [cosminnicula/react-ui-components#2]
Hello there, 

I'm just doing some due diligence and wondering if it's possible to use your library in a commercial project.  I realise that I've already forked it but I don't see a licence.

Obviously if you don't want to licence it under an OSS licence that is your choice and I'll delete my fork!  

Thanks,

Andy.

**Comment by cosminnicula** [comment]
I've added the license which grants using this library in commercial projects. Nevertheless, the Extended FixedDataTable is based on Facebook's Fixed Data Tables which is licensed BSD, and the Extended DropdownList is based on Jason Quense's  React Widgets which are licensed MIT.

**Comment by aphillipo** [comment]
Thanks!
